# docker-compose.yml
version: "3.9"
services:
  sentenialx:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: sentenialx:local
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8000:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DATABASE_URL=${DATABASE_URL:-postgresql://user:pass@db/sentenialx}
    volumes:
      - ./backend/app:/app/app
      - sentenialx_models:/models

volumes:
  sentenialx_models:
