apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: model-server
  namespace: sentenialx
spec:
  serviceName: "model-server"
  replicas: 2
  selector:
    matchLabels:
      app: model-server
  template:
    metadata:
      labels:
        app: model-server
    spec:
      nodeSelector:
        kubernetes.io/role: gpu
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: model-server
        image: your-docker-repo/sentenialx-modelserver:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MODEL_DIR
          value: "/models"
        - name: MODEL_NAME
          value: "70b"   # or "405b" - choose per StatefulSet
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /models
          name: models
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "192Gi"
          requests:
            cpu: "4"
            memory: "64Gi"
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: sentenialx-models-pvc
