apiVersion: v1
kind: Service
metadata:
  name: model-server
  namespace: sentenialx
spec:
  selector:
    app: model-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
